Save and retrieve favorites from LocalStorage.
marothon/lexicon-cocktail pull request #55
Opened 2024-09-25 09:26 UTC by angelstam

2024-09-25 09:31 UTC, marothon requested changes

2024-09-25 09:31 UTC, marothon commented on src/context/GlobalStateContext.tsx
> +  const favoritesStored = window.localStorage.getItem("favorites");
Sidoeffekter (dvs. användning av webbläsarens window api) måste ske i en useEffect

2024-09-25 09:32 UTC, marothon commented on src/context/GlobalStateContext.tsx
> +  const favoritesStored = window.localStorage.getItem("favorites");
Alternativt en custom hook

2024-09-25 09:51 UTC, angelstam commented on src/context/GlobalStateContext.tsx
> +  const favoritesStored = window.localStorage.getItem("favorites");
Men egentligen har den inga sidoeffekter som påverkar react. Den läser bara ett tillstånd som används när useState körs för [favorites, setFavorites]. Sedan skriver den till LocalStorage, men detta läses aldrig på något annat vis än ovan.

2024-09-25 11:15 UTC, marothon commented on src/context/GlobalStateContext.tsx
> +  const favoritesStored = window.localStorage.getItem("favorites");
Om man ska följa React's dokumentation slaviskt ska man använda useEffect när "externa system"  anropas, såsom "browser API" som localStorage är del av:https://react.dev/reference/react/useEffect
<img width="922" alt="image" src="https://github.com/user-attachments/assets/d03d734b-2671-4241-94d3-0c27b9251589">

2024-09-25 11:36 UTC, marothon commented on src/context/GlobalStateContext.tsx
> +  const favoritesStored = window.localStorage.getItem("favorites");
Maja gav ett bra exempel i gruppchatten:

```typescript
import React, { useState, useEffect } from 'react';

function MyComponent() {
  const [value, setValue] = useState('');

  // Läsa värdet från localStorage vid komponentens första rendering
  useEffect(() => {
    const savedValue = localStorage.getItem('myKey');
    if (savedValue) {
      setValue(savedValue);
    }
  }, []); // Tom array gör att denna effekt bara körs en gång (vid montering)

  // Spara värdet i localStorage varje gång det ändras
  useEffect(() => {
    if (value) {
      localStorage.setItem('myKey', value);
    }
  }, [value]); // Kör varje gång 'value' ändras

  return (
    <div>
      <input
        type="text"
        value={value}
        onChange={(e) => setValue(e.target.value)}
        placeholder="Enter a value"
      />
    </div>
  );
}

export default MyComponent;
```

2024-09-27 09:58 UTC, angelstam commented on src/context/GlobalStateContext.tsx
> +  const favoritesStored = window.localStorage.getItem("favorites");
Så om det hade stått så här istället menar du att det också hade krävt useEffect? För med den prestanda som LocalStorage har borde det vara ekvivalent i detta fall.

```
const favoritesStored = "{"11005":{"id":"11005","drink":"Dry Martini","drinkThumb":"https://www.thecocktaildb.com/images/media/drink/6ck9yi1589574317.jpg"}}";
```

På rad 36 och 44 skulle man kunna ersätta `window.localStorage.setItem("favorites", JSON.stringify(Object.fromEntries(oldFavorites)));` med t.ex. `console.log(JSON.stringify(Object.fromEntries(oldFavorites)));` för den har samma effekt på DOM:en.

2024-09-27 09:59 UTC, angelstam commented on src/context/GlobalStateContext.tsx
> +  const favoritesStored = window.localStorage.getItem("favorites");
test

2024-09-27 10:15 UTC, marothon approved these changes
Vi kör på med brasklappen att det ev. inte är OK enligt React standard.

2024-09-27 10:16 UTC, merged